name: publish app
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug

jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.2
        extensions: json, dom, curl, libxml, mbstring
        coverage: none

    - name: Install Pint
      run: composer global require laravel/pint

    - name: Run Pint
      run: pint

    - name: Commit linted files
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Fix code styling
  
    - name: Install Composer dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Run npm install and build
      run: |
        npm install
        npm run build

    - name: Optimize Laravel
      run: php artisan optimize:clear

    - name: Migrate database
      run: php artisan migrate 

    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        port: 21
        timeout: 60000
        exclude: |
          **/.git*
          **/.git*/**
          **/storage/**
